# Generated by Django 5.0.3 on 2024-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease_detector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
